### ISSUE TITLE
error by running?

### ISSUE THREAD

**Issue by Thanh-Binh** [marionleborgne/frequency-encoder#2]
Hi Marion,
I have just tested your code in python and got the following error. Do you know it? thanks

from frequency_encoder import FrequencyEncoder
sineEncoder = FrequencyEncoder(8,8,1,0,12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't instantiate abstract class FrequencyEncoder with abstract methods write

**Comment by rhyolight** [comment]
@Thanh-Binh It needs to be updated to work with NuPIC 1.0. I think it will need to provide some kind of serialization protocol for pycapnp.

**Comment by Thanh-Binh** [comment]
Hi Matt, thanks for your prompt response. Who can do it?

**Comment by rhyolight** [comment]
:man_shrugging:

**Comment by Thanh-Binh** [comment]
It is solved

**Comment by rhyolight** [comment]
@Thanh-Binh How did you solve it? 🤔

**Comment by Thanh-Binh** [comment]
Matt: i ported it completely into C++!
